#!/bin/bash

cd html

if [ ! -e tutorial-resources-ves ] ; then
  mkdir tutorial-resources-ves
fi
cd ../


for file in ./tutorials-ves/*.txt ; do

   check=`grep additional-files: $file | wc -l`
   if [ $check -gt 1 ] ; then
        echo Input files for tutorials should all be given in a single tarball. $file contains $check files >> errors-ves
   elif [ $check -gt 0 ] ; then
      resources=`grep additional-files: $file | sed -e 's/additional-files: //'`
     for addfile in $resources; do
        if test -d tutorials-ves/$addfile; then
          cd tutorials-ves
          tar czf ../html/tutorial-resources-ves/$addfile.tar.gz $addfile
          cd -
        else
          cp tutorials-ves/$addfile html/tutorial-resources-ves
        fi
     done
   fi

done

